import "dotenv/config";
import { randomUUID } from "node:crypto";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { pool } from "../src/db/pool.js";
import { withTenantTransaction } from "../src/db/withTenantTransaction.js";

// Phase 6A §6: idempotent dev-only identity seed. Never insert a second
// "vireon-dev" tenant on re-run -- look up by stable name first, create
// only what's missing. No new tables, no auth, no sessions -- reuses the
// Phase 1 tenants/users/actors/workspaces/projects schema exactly as-is.

const TENANT_NAME = "vireon-dev";
const USER_EMAIL = "dev@vireon.local";
const ACTOR_NAME = "Vireon Dev Actor";
const WORKSPACE_NAME = "vireon-dev-workspace";
const PROJECT_NAME = "vireon-dev-project";

interface DevIdentity {
  tenantId: string;
  userId: string;
  actorId: string;
  workspaceId: string;
  projectId: string;
}

async function findOrCreateTenant(): Promise<string> {
  const existing = await pool.query("SELECT id FROM tenants WHERE name = $1 LIMIT 1", [TENANT_NAME]);
  if (existing.rows[0]) return existing.rows[0].id as string;

  const id = randomUUID();
  await pool.query("INSERT INTO tenants (id, name) VALUES ($1, $2)", [id, TENANT_NAME]);
  return id;
}

async function findOrCreateRest(tenantId: string): Promise<Omit<DevIdentity, "tenantId">> {
  return withTenantTransaction(tenantId, async (client) => {
    const existingUser = await client.query("SELECT id FROM users WHERE tenant_id = $1 AND email = $2 LIMIT 1", [
      tenantId,
      USER_EMAIL,
    ]);
    let userId = existingUser.rows[0]?.id as string | undefined;
    if (!userId) {
      userId = randomUUID();
      await client.query("INSERT INTO users (id, tenant_id, email, display_name) VALUES ($1, $2, $3, $4)", [
        userId,
        tenantId,
        USER_EMAIL,
        "Vireon Dev User",
      ]);
    }

    const existingActor = await client.query(
      "SELECT id FROM actors WHERE tenant_id = $1 AND actor_name = $2 LIMIT 1",
      [tenantId, ACTOR_NAME],
    );
    let actorId = existingActor.rows[0]?.id as string | undefined;
    if (!actorId) {
      actorId = randomUUID();
      await client.query(
        `INSERT INTO actors (id, tenant_id, actor_type, actor_name, actor_role, user_id, acting_system)
         VALUES ($1, $2, $3, $4, $5, $6, $7)`,
        [actorId, tenantId, "human", ACTOR_NAME, "requesting_user", userId, "phase6a-dev-identity"],
      );
    }

    const existingWorkspace = await client.query(
      "SELECT id FROM workspaces WHERE tenant_id = $1 AND name = $2 LIMIT 1",
      [tenantId, WORKSPACE_NAME],
    );
    let workspaceId = existingWorkspace.rows[0]?.id as string | undefined;
    if (!workspaceId) {
      workspaceId = randomUUID();
      await client.query("INSERT INTO workspaces (id, tenant_id, name) VALUES ($1, $2, $3)", [
        workspaceId,
        tenantId,
        WORKSPACE_NAME,
      ]);
    }

    const existingProject = await client.query(
      "SELECT id FROM projects WHERE tenant_id = $1 AND name = $2 LIMIT 1",
      [tenantId, PROJECT_NAME],
    );
    let projectId = existingProject.rows[0]?.id as string | undefined;
    if (!projectId) {
      projectId = randomUUID();
      await client.query("INSERT INTO projects (id, tenant_id, workspace_id, name) VALUES ($1, $2, $3, $4)", [
        projectId,
        tenantId,
        workspaceId,
        PROJECT_NAME,
      ]);
    }

    return { userId, actorId, workspaceId, projectId };
  });
}

function writeEnvVars(identity: DevIdentity): void {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const envPath = path.join(__dirname, "..", ".env");

  const updates: Record<string, string> = {
    VIREON_DEV_TENANT_ID: identity.tenantId,
    VIREON_DEV_ACTOR_ID: identity.actorId,
    VIREON_DEV_WORKSPACE_ID: identity.workspaceId,
    VIREON_DEV_PROJECT_ID: identity.projectId,
  };

  const existingLines = existsSync(envPath) ? readFileSync(envPath, "utf8").split("\n") : [];
  const seenKeys = new Set<string>();
  const nextLines = existingLines.map((line) => {
    const match = /^([A-Z0-9_]+)=/.exec(line);
    if (match && Object.prototype.hasOwnProperty.call(updates, match[1]!)) {
      seenKeys.add(match[1]!);
      return `${match[1]}=${updates[match[1]!]}`;
    }
    return line;
  });

  const missingKeys = Object.keys(updates).filter((key) => !seenKeys.has(key));
  if (missingKeys.length > 0) {
    if (nextLines.length > 0 && nextLines[nextLines.length - 1]!.trim() !== "") {
      nextLines.push("");
    }
    nextLines.push("# Phase 6A dev identity -- generated by scripts/seedDevIdentity.ts, safe to regenerate");
    for (const key of missingKeys) {
      nextLines.push(`${key}=${updates[key]}`);
    }
  }

  writeFileSync(envPath, nextLines.join("\n"));
}

async function run(): Promise<void> {
  const tenantId = await findOrCreateTenant();
  const rest = await findOrCreateRest(tenantId);
  const identity: DevIdentity = { tenantId, ...rest };

  writeEnvVars(identity);

  console.log("Dev identity ready (idempotent -- safe to re-run):");
  console.log(`  tenantId:    ${identity.tenantId}`);
  console.log(`  actorId:     ${identity.actorId}`);
  console.log(`  workspaceId: ${identity.workspaceId}`);
  console.log(`  projectId:   ${identity.projectId}`);
  console.log("Written to .env as VIREON_DEV_TENANT_ID / VIREON_DEV_ACTOR_ID / VIREON_DEV_WORKSPACE_ID / VIREON_DEV_PROJECT_ID.");
}

run()
  .catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  })
  .finally(() => {
    void pool.end();
  });
